config/routes.rb
LocoTrades::Application.routes.draw do

  resources :posts do
    resources :comments
    resources :albums
  end
  devise_for :users
  root 'posts#index'
  match '/contact',       to: 'static_pages#contact',    via: 'get'
  match '/about',         to: 'static_pages#about',      via: 'get'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :post

  # validates :image, presence: true
  # validates :post_id, presence: true

  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  has_ancestry
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	belongs_to :user
	has_many :albums, dependent: :destroy
	accepts_nested_attributes_for :albums
	has_many :comments, :as => :commentable, dependent: :destroy

	default_scope -> { order('created_at DESC') }

	validates :user_id,   presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  validates :first_name, presence: true
  validates :last_name,  presence: true

  validates :username,   :uniqueness => { :case_sensitive => false }

  has_many :posts, dependent: :destroy
  has_many :comments

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
 before_action :set_post
 before_action :set_album, only: [:edit, :update, :destroy]
  

  private

  def album_params
    params.require(:album).permit(:image)
  end
  
  def set_post
    @post = Post.find(params[:post_id])
  end
  
  def set_album
    @album = @post.albums.find(params[:id])
  end
end

  
  
  
  
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_filter :configure_permitted_parameters, if: :devise_controller?
  


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @parent_id = params.delete(:parent_id)
    @commentable = find_commentable
    @comment = Comment.new( :parent_id => @parent_id, 
                            :commentable_id => @commentable.id,
                            :commentable_type => @commentable.class.to_s)

  end
  
  def create
    
    @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "Successfully posted an offer."
      PostMailer.offer_posted(@commentable.user).deliver #this is the mail code
      redirect_to @commentable
    else
      flash[:error] = "Error adding an offer."
    end
  end
 
  private
  def comment_params
  	params.require(:comment).permit(:content, :parent_id, :commentable_id, :commentable_type)
  end
  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:edit, :show, :update]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
  	@post = Post.new
    5.times { @post.albums.build }
  end

  def create
  	if current_user
  		@post = current_user.posts.build(post_params)
  		if @post.save
  			redirect_to @post, notice: 'Post was successfully created'
        # redirect_to new_post_album_path(@post), notice: 'Add images to your post below'
  		else
  			render 'new'
  		end
  	end
  end

  def edit
  end

  def update
  	if @post.update(post_params)
  		redirect_to @post, notice: 'Post was successfully updated.'
  	else
  		render 'edit'
  	end
  	
  end

  def index
    @search = Post.search(params[:q])
    @posts = @search.result.page(params[:page]).per(20)
    #@search.build_condition
  end

  def show
    @album = Album.new
    @album.post_id = @post.id

    @commentable = find_commentable
    @comments = @commentable.comments.arrange(:order => :created_at)
    @comment = Comment.new
  end

  def destroy
  	@post.destroy
  	redirect_to posts_url, notice: "the post has been deleted!"
  end

  private

  def set_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :description, :value, :category, :city, :state, :exchange, albums_attributes: [:image])
  end

  def correct_user
  	@post = current_user.posts.find_by(id: params[:id])
  	redirect_to(root_url , notice: "You don't have the right authorization to perform that action") if @post.nil?
  end

  def find_commentable
    return params[:controller].singularize.classify.constantize.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			content_tag(:div, render(comment), :class => "media")
		end.join.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/albums/_form.html.erb
<fieldset>
  <legend>Upload Images</legend>
    <%= form_for [ @post, @album ], :html => {:multipart => true } do |f| %>
    <div class="field">
      <%= f.file_field :image, id: 'subm-field' %><br>
    </div>
  
      <%= f.submit "Add images", class: 'button tiny radius', id: 'subm', disabled: 'add images first' %>
  
    <% end %>
</fieldset>

app/views/albums/new.html.erb
<div class="row">
  <fieldset>
    <legend>Upload Images</legend>
      <%= form_for [ @post, @album ], :html => {:multipart => true } do |f| %>
      <div class="field">
        <%= f.file_field :image, id: 'subm-field' %><br>
      </div>
    
        <%= f.submit "Add images", class: 'button tiny radius', id: 'subm', disabled: 'add images first' %>
    
      <% end %>
  </fieldset>
</div>

app/views/comments/_comment.html.erb
<!-- this is the comment.parent display -->
<div class="media-body">
	<div class="parent_comment_display">
		<p><%= simple_format( comment.content) %></p>
		<p class="comment_info">Posted <%= time_ago_in_words(comment.created_at) %> ago by 
			<strong>
				<% if comment.user.username? %>
				<%= comment.user.username %>
				<% else %>
				<%= comment.user.first_name %>
				<% end %>
			</strong></p>
	
	
	<!--this is the replay link -->
	<div class="actions">
		<%= link_to "Reply", new_polymorphic_path([@commentable, Comment.new], :parent_id => comment), class: "reply_button_for_comment" %>
	</div>
	<hr>
	</div>

	<!-- this is the comment.children display -->
	<div class="children_comment_display">
		<div class="nested_messages"><%= nested_comments(comment.children) %></div>
	</div>
	

</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
	<%= f.hidden_field :parent_id %>

	<div>
		<%= f.label :content, "offer", class: "new_comment_header" %><br>
		<%= f.text_area :content, placeholder: "Write your offer here", :rows => 4 %>
	</div>
	<%= f.submit "Post an offer", class: 'button radius' %>
<% end %>

app/views/comments/new.html.erb
<div class="row">
  <%= render 'layouts/alternate_subnav' %>
	<div class="large-12 columns">
		<h1>Reply</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/layouts/_alternate_subnav.html.erb
<div class= "row show-for-medium-up" id="alternate-subnav">
  <div class="large-2 columns" id="logo-topbar">
    <%= link_to image_tag("/app2dup.jpg"), root_path %>
  </div>
  <div class="large-10 columns">
    <div class="row" id="subnav-top">
      <div class="large-10  large-centered columns">
        <div>
          <dl class="sub-nav">
            <div class="subnav_hover_effect">
              <dd class="sign_register">
                <% if user_signed_in? %>
                <%= link_to "sign out", destroy_user_session_path, method: :delete %>
                <% else %>
                Hi!<%= link_to "sign in", new_user_session_path %>
                or<%= link_to "register", new_user_registration_path %>|
                <% end %>
              </dd>
              <dd><%= link_to "Home", root_path %>|</dd>
              <dd><%= link_to "About", about_path %>|</dd>
              <dd><%= link_to "Contact", contact_path %>|</dd>
              <dd><%= link_to "New Post", new_post_path %>|</dd>
            </div>
            <dd>
              <% if user_signed_in? %>
                <a href="#" data-dropdown="hover1" data-options="is_hover:true">My Account</a>
                <ul id="hover1" class="f-dropdown" data-dropdown-content>
                  <li><a href="#">My Trades</a></li>
                  <li><a href="#">bids/offers</a></li>
                  <li><a href="#">messages</a></li>
                  <li><a href="#">Trading History</a></li>
                  <li><a href="#">Watch list</a></li>
                </ul>
              <% end %>
            </dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer_bottom">
  <div class="row">
    <div class="medium-4 small-12 push-8 columns">
      <ul class="home-social">
        <li>
          <a href="http://www.twitter.com/LocoTrades">
            <span data-tooltip class="has-tip" title="Twitter">
              <i class="fi-social-twitter"></i>
            </span>
          </a>
        </li>
        
        <li>
          <a href="http://www.facebook.com/locotrades12">
            <span data-tooltip class="has-tip" title="Facebook">
              <i class="fi-social-facebook"></i>
            </span>
          </a>
        </li>
        
        <li>
          <a href="http://www.tumblr.com">
            <span data-tooltip class="has-tip" title="Tumblr">
              <i class="fi-social-tumblr"></i>
            </span>
          </a>
        </li>
        
        <li>
          <a href="http://www.plus.google.com">
            <span data-tooltip class="has-tip" title="Google-plus">
              <i class="fi-social-google-plus"></i>
            </span>
          </a>
        </li>
        
        <li>
          <a href="http://www.instagram.com">
            <span data-tooltip class="has-tip" title="Instagram">
              <i class="fi-social-instagram"></i>
            </span>
          </a>
        </li>
      </ul>
    </div>
    <div class="medium-8 small-12 pull-4 columns" id= "main_footer_links">
     
      <ul class="other_footer_links">
        <li class="footer_logo"><%= link_to "Loco Trades", root_path %></li>
        <li><a href="#">Posts</a></li>
        <li><a href="#">Contact</a></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><a href="#" data-reveal-id="myModal" data-reveal>privacy policy</a></li>
        <li><a href="#">Newsletter</a></li>
        <li><a href="#">Specials</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_subnav.html.erb
<div class="row show-for-medium-up" id="subnav-top">
	<div class="large-9  large-centered columns">
		<div>
		  <dl class="sub-nav">
        <div class="subnav_hover_effect">
          <dd class="sign_register">
            <% if user_signed_in? %>
            <%= link_to "sign out", destroy_user_session_path, method: :delete %>
            <% else %>
            Hi!<%= link_to "sign in", new_user_session_path %>
            or<%= link_to "register", new_user_registration_path %>|
            <% end %>
          </dd>
          <dd><%= link_to "Home", root_path %>|</dd>
          <dd><%= link_to "About", about_path %>|</dd>
          <dd><%= link_to "Contact", contact_path %>|</dd>
          <dd><%= link_to "New Post", new_post_path %>|</dd>
        </div>
        <dd>
          <% if user_signed_in? %>
            <a href="#" data-dropdown="hover1" data-options="is_hover:true">My Account</a>
            <ul id="hover1" class="f-dropdown" data-dropdown-content>
              <li><a href="#">My Trades</a></li>
              <li><a href="#">bids/offers</a></li>
              <li><a href="#">messages</a></li>
              <li><a href="#">Trading History</a></li>
              <li><a href="#">Watch list</a></li>
            </ul>
          <% end %>
        </dd>
		  </dl>
		</div>
	</div>
</div>

app/views/layouts/_topbar.html.erb
<form>
	<div class="row" >
		<div class="large-2 columns" id="logo-topbar">
			<%= link_to image_tag("/app2dup.jpg"), root_path %>
		</div>
		<div class="large-10 small-12 columns">
			<div class="row collapse">
				<div class="small-7 columns">
					<input type="text" placeholder="Search">
				</div>
				<div class="small-3 columns">
					<select>
							<option>All categories</option>
							<option>Art</option>
							<option>Books and Movies</option>
							<option>Clothing</option>
							<option>Collectibles</option>
							<option>Computers</option>
							<option>Construction Materials</option> 
							<option>Crafts & Hobbies</option>
							<option>Entertainment</option>
							<option>Farm & Ranch</option>
							<option>Food & bevarages</option>
							<option>Free Stuff</option>
							<option>Gardening</option>
							<option>Gifts</option>
							<option>Health& Beauty</option>
							<option>Home & Electronics</option>
							<option>Industrial & Commercial</option>
							<option>Jewelry & Gemstones</option>
							<option>Medical Supplies</option>
							<option>Miscellaneous</option>
							<option>Motorworld</option>
							<option>Music</option>
							<option>Office Supplies</option>
							<option>Others</option>
							<option>Pets/Animals</option>
							<option>Photography</option>
							<option>Real Estate</option>
							<option>Services</option>
							<option>Sporting Goods & Recreation</option>
							<option>Tools</option>
							<option>Toys & Games</option>
							<option>Vacation & Travel</option>
					</select>
				</div>
				<div class="small-2 columns">
					<a href="#" class="button postfix">Search</a>
				</div>
			</div>
		</div>
	</div>
</form>





<div class="row">
	<div class="large-12 columns">
	  <dl class="sub-nav" id="subnav2-homepage">
	    <dd><a href="#">Computers</a></dd>
	    <dd><a href="#">Entertainment</a></dd>
	    <dd><a href="#">Services</a></dd>
	    <dd><a href="#">Tools</a></dd>
	    <dd><a href="#">Motor World</a></dd>
	    <dd><a href="#">Collectables</a></dd>
	    <dd><a href="#">Home & Electronics</a></dd>
	  </dl>
	</div>
</div>

app/views/layouts/_topbar_mobile.html.erb
<nav class="top-bar show-for-small-only" data-topbar id="topbar_small">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Loco Trades</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "sign in", new_user_session_path %></li>
        <li><%= link_to "register", new_user_registration_path %></li>
      <% end %>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "New Post", new_post_path %></li>
      <% if user_signed_in? %>
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li><a href="#">My Trades</a></li>
          <li><a href="#">bids/offers</a></li>
          <li><a href="#">messages</a></li>
          <li><a href="#">Trading History</a></li>
          <li><a href="#">Watch list</a></li>
        </ul>
      </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,300' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Loco Trades" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/topbar_mobile" %>
      <div class="row">
        <div id= "flash-notice"> 
          <% flash.each do |key, value| %>
            <div class= "alert alert-box <%= key %> radius"><%= value %>
               <a href="#" class="close">&times;</a>
            </div>
            
          <% end %>
        </div>
      </div>

      <%= yield %>
      <div class="push"></div>
    </div>
      <%= render 'layouts/footer' %>
      <%= render 'devise/shared/privacy_policy' %>
    
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
      $(document).ready(
        function(){
            $('#subm-field').change(
                function(){
                    if ($(this).val()) {
                        $('#subm').attr('disabled',false); 
                    } 
                }
                );
        });
    </script>
  </body>
</html>

app/views/posts/_album.html.erb
<ul class="clearing-thumbs" id="show_images" data-clearing> 
  <li><%= link_to(image_tag(album.image_url(:small)), album.image_url) %></li>
</ul>

  

app/views/posts/_form.html.erb
<div class="post_form">
	<%= form_for @post do |f| %>
		
		<% if @post.errors.any? %>
			<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>

		<fieldset>
			<legend>Choose A Category</legend>
			<%= f.label :category %>
			<%= f.select :category, ["",  "Art", "Books and Movies", "Clothing","Collectibles", "Computers & Related", "Construction Materials", "Crafts & Hobbies", "Entertainment", "Farm & Ranch","Food & Beverages","Free Stuff", "Gardening","Gifts", "Health & Beauty", "Home & Electronics","Inductrial & Commercial", "Jewelry & Gemstones", "Medical Supplies","Miscellaneous","Motorworld","Music","Office Supplies","Others","Pets/Animals","Photography","Real Estate & Notes","Services","Sporting Goods & Recreation","Tools","Toys & Games","Vacation & Travel"] %>
		</fieldset>

		<fieldset>
			<legend>Describe Your Item</legend>
			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :description %>
			<%= f.text_area :description %>

			<%= f.label :value %>
			<%= f.text_field :value %>

			<%= f.label :exchange %>
			<%= f.text_field :exchange %>
		</fieldset>

		<fieldset>
			<legend>Location</legend>
			<%= f.label :city %>
			<%= f.text_field :city, class: "post_form_city" %>

			<%= f.label :state %>
			<%= f.text_field :state, class: "post_form_state" %>

		</fieldset>
     <% if @post.id? %>
         <p> update images </p>
      <% else %>
        <fieldset>
        <legend>Upload Images</legend>
         
          
          <% number = 0 %>
          <% if number <= 5 %>
          <%= f.fields_for :albums do |album| %>
            <%= album.label :image, "image ##{number += 1}" %>
            <%= album.file_field :image %>
          <% end %>
          <% end %>
        </fieldset>
    <% end %>
		
		

		

		

		

		<%= f.submit class: 'button radius post_form_submit_button' %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <%= render 'layouts/alternate_subnav' %>
	<h1>Edit Post</h1>
	<%= render 'form' %>
  <div>
    <%= link_to "delete post", @post, method: :delete, class: "button tiny alert radius" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <%= render 'layouts/alternate_subnav' %>
	<h1>Create New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/alternate_subnav' %>
<div class="row" id= "show_page_id">
  <div class="row">
    <div class="small-5 columns">
        <% if @post.albums.any? %>
          <ul class="clearing-thumbs" id="show_images" data-clearing> 
           
              <% for album in @post.albums do %>
                <li><%= link_to(image_tag(album.image_url), album.image_url) %></li>
              <% end %>
          </ul>
      
        <% else %>
         
        <% end %>
  	</div>
    <div class="small-7 small-centered columns">
      <h4><%= @post.title %></h4>
      <p>Value: <strong><%= @post.value %></strong></p>
      <p>Exchange Item: <strong><%= @post.exchange %></strong></p>
      <p>Location: <strong><%= @post.city %>, <%= @post.state %></strong></p>
      <% unless @post.user == current_user %>
        <a href="#" class="button radius" data-reveal-id="myOffersModal" data-reveal>Make an offer</a>
      <% end %>
    </div>
  </div>
  <dl class="tabs" data-tab>
  <dd class="active"><a href="#panel2-1">Description</a></dd>
  <dd><a href="#panel2-2">Value</a></dd>
  <dd><a href="#panel2-3">Exchange</a></dd>
  <dd><a href="#panel2-4">Location</a></dd>
</dl>
<div class="tabs-content" id="show_tabs_content">
  <div class="content active" id="panel2-1">
    <p><%= @post.description %></p>
  </div>
  <div class="content" id="panel2-2">
    <p><%= @post.value %></p>
  </div>
  <div class="content" id="panel2-3">
    <p><%= @post.exchange %></p>
  </div>
  <div class="content" id="panel2-4">
    <p><%= @post.city %>, <%= @post.state %></p>
  </div>
</div>
  
  <div>
	<% if @post.user == current_user %>
    <div>
      <%= link_to "edit post", edit_post_path(@post), class: "button tiny round" %>
    </div>
	<% end %>
</div>
  

<div>
  <% unless @post.user == current_user %>
    <a href="#" class="button radius" data-reveal-id="myOffersModal" data-reveal>Make an Offer</a>
    <div id="myOffersModal" class="reveal-modal" data-reveal>
      <%= render "comments/form" %>
      <a class="close-reveal-modal">&#215;</a>
    </div>
  <% end %>
  
  <% if @comments.any? %>
  <h4>Current Offers</h4>
  <div class="list_of_offers"><%= nested_comments @comments %></div>
  <% else %>
  <h4>No offers yet</h4>
  <% end %>
  
</div>


</div>

app/views/static_pages/about.html.erb
<div class="row">
  <%= render 'layouts/alternate_subnav' %>
  <div class="row">
	  <div class="large-12 large-centered columns">
		  <h2 class="about-heading">About Loco Trades</h2>
    </div>
  </div>
  
  <div class="large-12 columns">
    <blockquote>
      Our mission is to offer the best platform to search and find unbelievable deals. Our vision is with a simple click of 
      a button you will get items and ideas you never thought you could own. Visit us and make your move a crazy trade  
      <cite>Lloyd Gatobu, Founder</cite>
    </blockquote>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
  <%= render 'layouts/alternate_subnav' %>
	<div class="large-12">
		
	</div>
</div>
<br>
<br>
<div class="row">
  <script type='text/javascript'>var _fo=_fo||[];_fo.push({'d':'center','c':'f0fef3','i':1349});if(typeof fce=='undefined'){var s=document.createElement('script');s.type='text/javascript';s.async=true;s.src=('https:'==window.location.protocol?'https://':'http://')+'formcrafts.com/js/fc.js';var fi=document.getElementsByTagName('script')[0];fi.parentNode.insertBefore(s,fi);fce=1;}</script><div id='f0fef3'><a href='https://formcrafts.com/a/1349'>contact Us form</a></div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
	<div class="large-9 columns">
		<ul class="example-orbit" data-orbit>
			<li>
				<img src="/andromeda-orbit.jpg" alt="slide 1" />
				<div class="orbit-caption">Caption One.</div>
			</li>
			<li>
				<img src="/satelite-orbit.jpg" alt="slide 2" />
				<div class="orbit-caption">Caption Two.</div>
			</li>
			<li>
				<img src="/launch-orbit.jpg" alt="slide 3" />
				<div class="orbit-caption">Caption Three.</div>
			</li>
		</ul>
	</div>

	<div class="large-3 columns">
		<div class="panel" id="home_page_panel">
			<h4>Welcome to Loco Trades</h4>
			<p>We are the go to site for barter trading</p>
			<p>Check out the Items that are being traded below</p>
		</div>
	</div>
</div>


<div class="row">
	<%if @posts.any? %>
		<% @posts.each do |post| %>
			<div class="large-3 columns">
				<div class="panel" id="post_index_panel">
					<% if post.albums.any? %>
						<%= link_to(image_tag(post.albums.first.image_url(:thumb)), post) %>
           <% else %>
					<% end %>
          <div class="post-info-display">
            <p class="post_index_title"><%= truncate(post.title, length: 55) %></p>
            <p class="post_index_description"><%= truncate(post.description, length: 60) %></p> 
            <p class="post_index_value"><%= post.value %></p>
            <p class="post_index_seller"><i class="fi-torso"></i> <%= post.user.username %></p>
            <div class="index_button_show"><%= (link_to "make an offer", post, class: "button tiny radius") unless post.albums.any? %></div>
          </div>
				</div>
			</div>
		<% end %>
	<% end %>
</div>




<form>
	<div class="row" >
		<div class="large-2 columns" id="logo-topbar">
			<%= link_to image_tag("/app2dup.jpg"), root_path %>
		</div>
    <%= search_form_for @search do |f| %>
		<div class="large-10 small-12 columns">
			<div class="row collapse">
				<div class="small-7 columns">
					<%= f.text_field :description_cont %>
				</div>
				<div class="small-3 columns">
					<%= f.select :category_cont, ["",  "Art", "Books and Movies", "Clothing","Collectibles", "Computers & Related", "Construction Materials", "Crafts & Hobbies", "Entertainment", "Farm & Ranch","Food & Beverages","Free Stuff", "Gardening","Gifts", "Health & Beauty", "Home & Electronics","Inductrial & Commercial", "Jewelry & Gemstones", "Medical Supplies","Miscellaneous","Motorworld","Music","Office Supplies","Others","Pets/Animals","Photography","Real Estate & Notes","Services","Sporting Goods & Recreation","Tools","Toys & Games","Vacation & Travel"] %>
				</div>
				<div class="small-2 columns">
          <div class="button postfix"><%= f.submit "Search" %></div>
    <% end %>
				</div>
			</div>
		</div>
	</div>
</form>